import './sass/main.scss';
import showMovieGallery from './js/showMovieGallery';
import './js/headerMarkup';
import './js/fetch-by-name';
import './js/filmInfoModalCreate';
import './js/footerModalOpen';
import './js/pagination';
import '@fortawesome/fontawesome-free/js/all.js';
import './js/theme-switcher';
import './js/slider';
showMovieGallery();
