import './sass/main.scss';
import './js/configuration';
import './js/saveConfiguration';
import './js/showMovieGallery';
import './js/headerMarkup';
import './js/fetch-by-name';
import './js/filmInfoModalCreate';
import './js/footerModalOpen';
import './js/add-to-watched';
import './js/pagination'
import '@fortawesome/fontawesome-free/js/all.js';
import './js/theme-switcher';
